# Generated by Django 3.0.8 on 2020-09-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_auto_20200914_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(blank=True, default='delhi.jpg', null=True, upload_to=''),
        ),
    ]
