# Generated by Django 3.0.8 on 2020-09-16 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_buy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='cart_image',
            new_name='order_image',
        ),
    ]
